### PR TITLE
Add adjustments for vcpkg

### PR DESCRIPTION
**Pull request by ngrodzitski**

### CODE REVIEW

**Comment by eao197** [comment]
I don't like very long names like "RESTINIO_DEPENDENCY_RESOLVE_HINT_FMT". It's almost impossible to write such a name by hand without a mistake.

Can we use something shorter? Like "RESTINIO_DEP_FMT" and "RESTINIO_DEP_LLHTTP" (with allowed values like "system", "find" and "local")?

**Comment by eao197** [comment]
Short names are much better, thanks you!

But can we use "find" instead of "find_package"?
I can understand if we have to introduce another alternative like "find_dependency" in the near future and there will be significant distinction between "find_package" and "find_dependency". But if we have no such plans, may be just "find" is the best?

**Comment by ngrodzitski** [comment]
> Short names are much better, thanks you!
> 
> But can we use "find" instead of "find_package"? I can understand if we have to introduce another alternative like "find_dependency" in the near future and there will be significant distinction between "find_package" and "find_dependency". But if we have no such plans, may be just "find" is the best?

Then I propose "package" as `[system, local, package]` looks more logical to me then `[system, local, find]`?

**Comment by eao197** [comment]
> Then I propose "package" as [system, local, package] looks more logical to me than [system, local, find]?

I'm afraid it would be hard to explain how "package" differs from "system" if a system package management is used for installing packages like "boost", "fmt" and "llhttp".

If you don't want to make another rename then I can do it.

**Comment by eao197** [comment]
Another alternative to "package" and "find": "config".
So we can have: "system" (installed somewhere in the system by system package manager), "local" (present in the project's source tree) and "config" (the config has to be found via `find_package`).

**Comment by eao197** [comment]
It's replaced by #196

**Pull request closed without merging**
