### PR TITLE
fix: warning C4100 unreferenced formal parameter

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by eao197** [comment]
Thanks for your PR.
I know about that issue, but had no time to fix it yet :(
There is a more simple solution, and I plan to apply it today or tomorrow.

**Comment by Milerius** [comment]
Great thank's a lot

**Comment by Milerius** [comment]
Is it possible to have a full release 5.0.2 with it ?

**Comment by eao197** [comment]
It will, probably, be 0.5.1.1.

**Comment by Milerius** [comment]
It's will be really nice for people using CMake fetch content

**Comment by eao197** [comment]
Version 0.5.1.1 is fixed as tag.

**Pull request closed without merging**
